USE bdd_absence;

#Insertion de 300 enfants et relations parents

insert into child (first_name, last_name, class_id, gender) values ('Dorree', 'Penfold', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ravid', 'Thorrington', 13, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ethel', 'Iston', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Wye', 'Agronski', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Patrick', 'Davenhall', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Biron', 'Talmadge', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Cooper', 'Pyer', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Merrick', 'Comoletti', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Lucila', 'Cassley', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Shell', 'Levin', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Kinny', 'Woolward', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Tabby', 'Casserly', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Thelma', 'Henrion', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Ringo', 'Mennithorp', 14, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Darlene', 'Delve', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Sada', 'Gritten', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Gerianne', 'Havile', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ferdie', 'Everist', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Deloria', 'Pitkaithly', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Janifer', 'Garrigan', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Base', 'Tunn', 14, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Jackie', 'Baggallay', 10, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Lanny', 'Mickleborough', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Aurea', 'Pinck', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Grantley', 'Gytesham', 6, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Prinz', 'Balsdone', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Audy', 'Addy', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Mordy', 'Sorensen', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Dede', 'Nutbrown', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Alexina', 'De Maine', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Emery', 'Sodory', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Rozamond', 'Savell', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jimmie', 'Kyte', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Danette', 'Monteith', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Carlee', 'Overstreet', 15, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Feliks', 'Hatherall', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Reeba', 'Reschke', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Con', 'Restieaux', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Marji', 'Grinval', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Van', 'Gilstin', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Rikki', 'Durber', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Ginni', 'Bodleigh', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Sheree', 'Grishankov', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Estevan', 'Adriani', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Rey', 'Pieracci', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Flory', 'Hulland', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Emmett', 'Papa', 15, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Reinald', 'Hairsine', 10, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Florrie', 'Ruppeli', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Markus', 'Tardiff', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Isa', 'Moorerud', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Celine', 'Dikelin', 8, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Craig', 'Whaymand', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Lilith', 'Moorhead', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Wilhelm', 'Quincey', 13, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jen', 'Scroyton', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Krista', 'Larwood', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Anne', 'Dakers', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Linnea', 'O''Lahy', 8, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jobyna', 'Thornham', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Nickie', 'Pointin', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Kirbee', 'Chalcraft', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Gauthier', 'Giorgini', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Reena', 'Stagge', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Beilul', 'Coulthard', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Davida', 'McClenan', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Lucy', 'Shine', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Arvin', 'Brithman', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Anitra', 'Beane', 14, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Mattie', 'Canelas', 8, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Faustina', 'Glozman', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jennette', 'Dohrmann', 10, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Mufi', 'Craisford', 13, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Lissy', 'Gulberg', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Dee', 'Tretter', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Daffi', 'Ales0', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Amaleta', 'Goor', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Mariele', 'Radmore', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Randolf', 'Cay', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Jeanette', 'Herity', 5, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Zackariah', 'Wallege', 10, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Inger', 'MacRory', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Marietta', 'Tilburn', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Wye', 'Walters', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Luce', 'Gehricke', 14, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Camey', 'Lohden', 10, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Orland', 'Denniston', 3, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Mitzi', 'Downham', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Isac', 'Rands', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Hillier', 'Robinet', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Rawley', 'MacAndreis', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Monica', 'Collinge', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Derry', 'Wankel', 10, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Odette', 'Cudde', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Brinn', 'Munden', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Rutger', 'Dilley', 6, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Gabriel', 'Aylmer', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Nevsa', 'Ridding', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Hercules', 'Ahrendsen', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Irving', 'Duckerin', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Melinda', 'Hannis', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Junia', 'Giveen', 4, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Mortie', 'Rowes', 14, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Velvet', 'Rosenwald', 4, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Elmira', 'Briant', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ave', 'Byas', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Vernor', 'Swindon', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Izabel', 'Aitkin', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Cleo', 'Swapp', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Charmaine', 'Hopkyns', 6, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Anne-marie', 'Thornhill', 10, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Drew', 'Severs', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Hagen', 'Toland', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Brena', 'Manuele', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Berty', 'Paffett', 5, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ilsa', 'Batcock', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Dana', 'Oakhill', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Farah', 'Plait', 13, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Tonia', 'Cawthera', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Guthrey', 'Tanser', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Miguelita', 'Gulliver', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Rosabelle', 'Janaszewski', 10, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Zena', 'Abelson', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Theodosia', 'Pechell', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Catherin', 'Jewel', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Lorain', 'Mitchinson', 10, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Balduin', 'Pittway', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Zebulon', 'Cejka', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ilysa', 'Boyen', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Prent', 'Dore', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Tull', 'Greathead', 4, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Loreen', 'Tuckwell', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Patricio', 'Clery', 4, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ario', 'Masedon', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Doy', 'Oselton', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Darsey', 'Elcomb', 13, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Valentine', 'Spinola', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Davina', 'Faunch', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ailene', 'Goodson', 10, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Asa', 'Romayne', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Katherina', 'Fennick', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Chaunce', 'Stallon', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Monroe', 'Roast', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Stacia', 'Reskelly', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Nelie', 'Streatfeild', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Fernando', 'Buscher', 8, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Osbert', 'Dewey', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Shalna', 'Ibbs', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Dolli', 'Murrock', 3, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Karrah', 'Gurney', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Alberta', 'Mingardi', 9, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Peta', 'Lloyd', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Karlie', 'Holmyard', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Brande', 'Pedrozzi', 6, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Cesaro', 'Belding', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Pierson', 'De Matteis', 8, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Denney', 'Ausiello', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Millicent', 'Gopsall', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Clark', 'Scupham', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Noellyn', 'Beet', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Mervin', 'Gainsburgh', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Norry', 'Ritelli', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Kathlin', 'Semour', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Hertha', 'Landsberg', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Maurice', 'Bagnall', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jeanine', 'Alexandersen', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Alistair', 'Girdwood', 5, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Kiley', 'Form', 15, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Eberto', 'Skitt', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Kimbell', 'Kolin', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Rancell', 'Veschambre', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Angelique', 'Gyrgorwicx', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Faber', 'Lackham', 4, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Gayle', 'Stronack', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ferrel', 'Lage', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jorgan', 'Erwin', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Camella', 'Peakman', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Cristi', 'Yude', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Obediah', 'Jan', 5, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Dolli', 'Shelley', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Cale', 'Nunes Nabarro', 8, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Martina', 'Faughny', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Caritta', 'Twigger', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Sharona', 'Garoghan', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Celesta', 'Perryn', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Demetra', 'Newcomb', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Iosep', 'Grellier', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Jarad', 'Ludlow', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Helene', 'Gasnell', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Valentina', 'Canland', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Diane', 'Curless', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Joeann', 'Lubomirski', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Gianna', 'McColley', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ardine', 'Mack', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Elbert', 'Wenden', 14, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Maje', 'O''Moylan', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jamal', 'Snugg', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Piper', 'Fones', 10, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Bar', 'Jann', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Whitby', 'Brockhurst', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Luisa', 'Habershaw', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Alanson', 'Gatlin', 11, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Minna', 'Ausher', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Nevin', 'MacIlriach', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Tabatha', 'Achromov', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Jessa', 'Hallas', 13, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Urbain', 'Pecht', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Donny', 'Purcell', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Emanuele', 'Tersay', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Kath', 'Stancer', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Lynea', 'Glendza', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jorie', 'Domelow', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Rianon', 'Tallis', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Beauregard', 'Whinney', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Wallie', 'Boud', 5, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Elinore', 'Sieve', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Abigail', 'Michelin', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Gaylord', 'Miles', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Sunshine', 'Burton', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Rolfe', 'Cornilli', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Sheeree', 'Casale', 3, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Adrienne', 'McCracken', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ellary', 'Van der Kruys', 8, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Royall', 'deKnevet', 3, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Averill', 'Lassey', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Hendrik', 'Simeone', 8, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Fabiano', 'Bantock', 5, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Hadria', 'Merrin', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Darell', 'Earengey', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Bonnie', 'Abrahart', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Cathrin', 'Paulisch', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Justinn', 'Guilfoyle', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Cathe', 'Turnor', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Huntington', 'Basill', 2, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Rudolph', 'Barrable', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Lulita', 'De Gowe', 10, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Tiebold', 'Jeske', 15, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Margarita', 'Roseaman', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Ulrich', 'Ibeson', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Nils', 'Kellie', 15, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Mollie', 'Mack', 10, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Kristopher', 'Iwanowicz', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Harriett', 'Vasyagin', 10, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Britney', 'Petow', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Camey', 'Reddoch', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Brandy', 'Risson', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Elladine', 'Pawlett', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Leo', 'Capner', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Burg', 'Hutten', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Itch', 'Struthers', 1, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Samantha', 'Pilgram', 1, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Nolana', 'Cullingworth', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Fayette', 'Gristwood', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Jaquenetta', 'Staunton', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Randy', 'Wagenen', 7, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Dixie', 'Lyard', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Torey', 'Horrell', 9, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Rose', 'Dunphie', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Leonora', 'Grunson', 14, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Nissy', 'Claiden', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Kamillah', 'McRobbie', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Rob', 'Birden', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Legra', 'Rothera', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Von', 'Dimic', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Rafael', 'Cheetham', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Dawna', 'Badby', 13, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Conroy', 'Rosenkranc', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Agneta', 'Mazzey', 12, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Mahalia', 'Bucklan', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Patrizio', 'Newing', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Husain', 'Duley', 8, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Jami', 'Cracknell', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Tim', 'Revelle', 3, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Sheree', 'Rawlison', 13, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Blinni', 'Gehricke', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Ahmed', 'Anyene', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Zachariah', 'Wren', 4, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jacques', 'Ragg', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Gavan', 'Drepp', 16, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Niels', 'Loomis', 7, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Trueman', 'Mountcastle', 14, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Philippa', 'Grimmer', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Brinn', 'Metson', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Reta', 'Ricoald', 6, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Kynthia', 'Coalburn', 15, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Wildon', 'O''Corhane', 5, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Myrtice', 'Harsnipe', 6, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Marlie', 'Mansell', 3, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Wenda', 'Gierok', 13, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Lesya', 'Dundin', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Cortney', 'Eakins', 14, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Hugues', 'Shepeard', 4, 'f');
insert into child (first_name, last_name, class_id, gender) values ('Omero', 'Dreger', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Jermaine', 'Clampin', 3, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Kermit', 'Flewitt', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Cathryn', 'Overal', 12, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Minne', 'Walters', 2, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Josey', 'Cartan', 11, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Hamel', 'Benzie', 16, 'm');
insert into child (first_name, last_name, class_id, gender) values ('Salvador', 'Gowler', 16, 'f');


insert into child_parent (child_id, parent_id) values (1, 91);
insert into child_parent (child_id, parent_id) values (2, 14);
insert into child_parent (child_id, parent_id) values (3, 110);
insert into child_parent (child_id, parent_id) values (4, 86);
insert into child_parent (child_id, parent_id) values (5, 136);
insert into child_parent (child_id, parent_id) values (6, 149);
insert into child_parent (child_id, parent_id) values (7, 111);
insert into child_parent (child_id, parent_id) values (8, 134);
insert into child_parent (child_id, parent_id) values (9, 114);
insert into child_parent (child_id, parent_id) values (10, 132);
insert into child_parent (child_id, parent_id) values (11, 46);
insert into child_parent (child_id, parent_id) values (12, 30);
insert into child_parent (child_id, parent_id) values (13, 62);
insert into child_parent (child_id, parent_id) values (14, 30);
insert into child_parent (child_id, parent_id) values (15, 35);
insert into child_parent (child_id, parent_id) values (16, 140);
insert into child_parent (child_id, parent_id) values (17, 108);
insert into child_parent (child_id, parent_id) values (18, 83);
insert into child_parent (child_id, parent_id) values (19, 143);
insert into child_parent (child_id, parent_id) values (20, 120);
insert into child_parent (child_id, parent_id) values (21, 47);
insert into child_parent (child_id, parent_id) values (22, 60);
insert into child_parent (child_id, parent_id) values (23, 87);
insert into child_parent (child_id, parent_id) values (24, 44);
insert into child_parent (child_id, parent_id) values (25, 141);
insert into child_parent (child_id, parent_id) values (26, 140);
insert into child_parent (child_id, parent_id) values (27, 62);
insert into child_parent (child_id, parent_id) values (28, 71);
insert into child_parent (child_id, parent_id) values (29, 130);
insert into child_parent (child_id, parent_id) values (30, 103);
insert into child_parent (child_id, parent_id) values (31, 106);
insert into child_parent (child_id, parent_id) values (32, 119);
insert into child_parent (child_id, parent_id) values (33, 36);
insert into child_parent (child_id, parent_id) values (34, 34);
insert into child_parent (child_id, parent_id) values (35, 123);
insert into child_parent (child_id, parent_id) values (36, 31);
insert into child_parent (child_id, parent_id) values (37, 5);
insert into child_parent (child_id, parent_id) values (38, 127);
insert into child_parent (child_id, parent_id) values (39, 19);
insert into child_parent (child_id, parent_id) values (40, 29);
insert into child_parent (child_id, parent_id) values (41, 49);
insert into child_parent (child_id, parent_id) values (42, 40);
insert into child_parent (child_id, parent_id) values (43, 80);
insert into child_parent (child_id, parent_id) values (44, 122);
insert into child_parent (child_id, parent_id) values (45, 133);
insert into child_parent (child_id, parent_id) values (46, 76);
insert into child_parent (child_id, parent_id) values (47, 64);
insert into child_parent (child_id, parent_id) values (48, 135);
insert into child_parent (child_id, parent_id) values (49, 48);
insert into child_parent (child_id, parent_id) values (50, 99);
insert into child_parent (child_id, parent_id) values (51, 145);
insert into child_parent (child_id, parent_id) values (52, 50);
insert into child_parent (child_id, parent_id) values (53, 10);
insert into child_parent (child_id, parent_id) values (54, 53);
insert into child_parent (child_id, parent_id) values (55, 54);
insert into child_parent (child_id, parent_id) values (56, 109);
insert into child_parent (child_id, parent_id) values (57, 64);
insert into child_parent (child_id, parent_id) values (58, 98);
insert into child_parent (child_id, parent_id) values (59, 37);
insert into child_parent (child_id, parent_id) values (60, 7);
insert into child_parent (child_id, parent_id) values (61, 73);
insert into child_parent (child_id, parent_id) values (62, 48);
insert into child_parent (child_id, parent_id) values (63, 35);
insert into child_parent (child_id, parent_id) values (64, 43);
insert into child_parent (child_id, parent_id) values (65, 75);
insert into child_parent (child_id, parent_id) values (66, 43);
insert into child_parent (child_id, parent_id) values (67, 97);
insert into child_parent (child_id, parent_id) values (68, 120);
insert into child_parent (child_id, parent_id) values (69, 103);
insert into child_parent (child_id, parent_id) values (70, 121);
insert into child_parent (child_id, parent_id) values (71, 55);
insert into child_parent (child_id, parent_id) values (72, 14);
insert into child_parent (child_id, parent_id) values (73, 81);
insert into child_parent (child_id, parent_id) values (74, 94);
insert into child_parent (child_id, parent_id) values (75, 50);
insert into child_parent (child_id, parent_id) values (76, 77);
insert into child_parent (child_id, parent_id) values (77, 9);
insert into child_parent (child_id, parent_id) values (78, 47);
insert into child_parent (child_id, parent_id) values (79, 125);
insert into child_parent (child_id, parent_id) values (80, 99);
insert into child_parent (child_id, parent_id) values (81, 12);
insert into child_parent (child_id, parent_id) values (82, 111);
insert into child_parent (child_id, parent_id) values (83, 11);
insert into child_parent (child_id, parent_id) values (84, 1);
insert into child_parent (child_id, parent_id) values (85, 84);
insert into child_parent (child_id, parent_id) values (86, 92);
insert into child_parent (child_id, parent_id) values (87, 79);
insert into child_parent (child_id, parent_id) values (88, 101);
insert into child_parent (child_id, parent_id) values (89, 119);
insert into child_parent (child_id, parent_id) values (90, 28);
insert into child_parent (child_id, parent_id) values (91, 10);
insert into child_parent (child_id, parent_id) values (92, 38);
insert into child_parent (child_id, parent_id) values (93, 142);
insert into child_parent (child_id, parent_id) values (94, 121);
insert into child_parent (child_id, parent_id) values (95, 145);
insert into child_parent (child_id, parent_id) values (96, 146);
insert into child_parent (child_id, parent_id) values (97, 53);
insert into child_parent (child_id, parent_id) values (98, 66);
insert into child_parent (child_id, parent_id) values (99, 126);
insert into child_parent (child_id, parent_id) values (100, 135);
insert into child_parent (child_id, parent_id) values (101, 74);
insert into child_parent (child_id, parent_id) values (102, 145);
insert into child_parent (child_id, parent_id) values (103, 10);
insert into child_parent (child_id, parent_id) values (104, 44);
insert into child_parent (child_id, parent_id) values (105, 19);
insert into child_parent (child_id, parent_id) values (106, 67);
insert into child_parent (child_id, parent_id) values (107, 47);
insert into child_parent (child_id, parent_id) values (108, 144);
insert into child_parent (child_id, parent_id) values (109, 97);
insert into child_parent (child_id, parent_id) values (110, 42);
insert into child_parent (child_id, parent_id) values (111, 37);
insert into child_parent (child_id, parent_id) values (112, 25);
insert into child_parent (child_id, parent_id) values (113, 114);
insert into child_parent (child_id, parent_id) values (114, 112);
insert into child_parent (child_id, parent_id) values (115, 79);
insert into child_parent (child_id, parent_id) values (116, 17);
insert into child_parent (child_id, parent_id) values (117, 34);
insert into child_parent (child_id, parent_id) values (118, 120);
insert into child_parent (child_id, parent_id) values (119, 102);
insert into child_parent (child_id, parent_id) values (120, 138);
insert into child_parent (child_id, parent_id) values (121, 137);
insert into child_parent (child_id, parent_id) values (122, 148);
insert into child_parent (child_id, parent_id) values (123, 132);
insert into child_parent (child_id, parent_id) values (124, 95);
insert into child_parent (child_id, parent_id) values (125, 143);
insert into child_parent (child_id, parent_id) values (126, 109);
insert into child_parent (child_id, parent_id) values (127, 78);
insert into child_parent (child_id, parent_id) values (128, 115);
insert into child_parent (child_id, parent_id) values (129, 147);
insert into child_parent (child_id, parent_id) values (130, 113);
insert into child_parent (child_id, parent_id) values (131, 11);
insert into child_parent (child_id, parent_id) values (132, 64);
insert into child_parent (child_id, parent_id) values (133, 142);
insert into child_parent (child_id, parent_id) values (134, 137);
insert into child_parent (child_id, parent_id) values (135, 67);
insert into child_parent (child_id, parent_id) values (136, 128);
insert into child_parent (child_id, parent_id) values (137, 150);
insert into child_parent (child_id, parent_id) values (138, 89);
insert into child_parent (child_id, parent_id) values (139, 67);
insert into child_parent (child_id, parent_id) values (140, 23);
insert into child_parent (child_id, parent_id) values (141, 14);
insert into child_parent (child_id, parent_id) values (142, 73);
insert into child_parent (child_id, parent_id) values (143, 2);
insert into child_parent (child_id, parent_id) values (144, 148);
insert into child_parent (child_id, parent_id) values (145, 51);
insert into child_parent (child_id, parent_id) values (146, 64);
insert into child_parent (child_id, parent_id) values (147, 95);
insert into child_parent (child_id, parent_id) values (148, 56);
insert into child_parent (child_id, parent_id) values (149, 43);
insert into child_parent (child_id, parent_id) values (150, 16);
insert into child_parent (child_id, parent_id) values (151, 117);
insert into child_parent (child_id, parent_id) values (152, 80);
insert into child_parent (child_id, parent_id) values (153, 118);
insert into child_parent (child_id, parent_id) values (154, 133);
insert into child_parent (child_id, parent_id) values (155, 113);
insert into child_parent (child_id, parent_id) values (156, 94);
insert into child_parent (child_id, parent_id) values (157, 83);
insert into child_parent (child_id, parent_id) values (158, 14);
insert into child_parent (child_id, parent_id) values (159, 18);
insert into child_parent (child_id, parent_id) values (160, 108);
insert into child_parent (child_id, parent_id) values (161, 33);
insert into child_parent (child_id, parent_id) values (162, 107);
insert into child_parent (child_id, parent_id) values (163, 119);
insert into child_parent (child_id, parent_id) values (164, 74);
insert into child_parent (child_id, parent_id) values (165, 69);
insert into child_parent (child_id, parent_id) values (166, 117);
insert into child_parent (child_id, parent_id) values (167, 109);
insert into child_parent (child_id, parent_id) values (168, 148);
insert into child_parent (child_id, parent_id) values (169, 88);
insert into child_parent (child_id, parent_id) values (170, 150);
insert into child_parent (child_id, parent_id) values (171, 119);
insert into child_parent (child_id, parent_id) values (172, 130);
insert into child_parent (child_id, parent_id) values (173, 123);
insert into child_parent (child_id, parent_id) values (174, 75);
insert into child_parent (child_id, parent_id) values (175, 143);
insert into child_parent (child_id, parent_id) values (176, 93);
insert into child_parent (child_id, parent_id) values (177, 42);
insert into child_parent (child_id, parent_id) values (178, 74);
insert into child_parent (child_id, parent_id) values (179, 2);
insert into child_parent (child_id, parent_id) values (180, 81);
insert into child_parent (child_id, parent_id) values (181, 68);
insert into child_parent (child_id, parent_id) values (182, 140);
insert into child_parent (child_id, parent_id) values (183, 34);
insert into child_parent (child_id, parent_id) values (184, 85);
insert into child_parent (child_id, parent_id) values (185, 14);
insert into child_parent (child_id, parent_id) values (186, 58);
insert into child_parent (child_id, parent_id) values (187, 117);
insert into child_parent (child_id, parent_id) values (188, 36);
insert into child_parent (child_id, parent_id) values (189, 78);
insert into child_parent (child_id, parent_id) values (190, 1);
insert into child_parent (child_id, parent_id) values (191, 78);
insert into child_parent (child_id, parent_id) values (192, 97);
insert into child_parent (child_id, parent_id) values (193, 13);
insert into child_parent (child_id, parent_id) values (194, 133);
insert into child_parent (child_id, parent_id) values (195, 97);
insert into child_parent (child_id, parent_id) values (196, 123);
insert into child_parent (child_id, parent_id) values (197, 90);
insert into child_parent (child_id, parent_id) values (198, 140);
insert into child_parent (child_id, parent_id) values (199, 144);
insert into child_parent (child_id, parent_id) values (200, 53);
insert into child_parent (child_id, parent_id) values (201, 40);
insert into child_parent (child_id, parent_id) values (202, 46);
insert into child_parent (child_id, parent_id) values (203, 72);
insert into child_parent (child_id, parent_id) values (204, 96);
insert into child_parent (child_id, parent_id) values (205, 39);
insert into child_parent (child_id, parent_id) values (206, 18);
insert into child_parent (child_id, parent_id) values (207, 22);
insert into child_parent (child_id, parent_id) values (208, 86);
insert into child_parent (child_id, parent_id) values (209, 85);
insert into child_parent (child_id, parent_id) values (210, 87);
insert into child_parent (child_id, parent_id) values (211, 116);
insert into child_parent (child_id, parent_id) values (212, 93);
insert into child_parent (child_id, parent_id) values (213, 116);
insert into child_parent (child_id, parent_id) values (214, 59);
insert into child_parent (child_id, parent_id) values (215, 66);
insert into child_parent (child_id, parent_id) values (216, 71);
insert into child_parent (child_id, parent_id) values (217, 7);
insert into child_parent (child_id, parent_id) values (218, 122);
insert into child_parent (child_id, parent_id) values (219, 51);
insert into child_parent (child_id, parent_id) values (220, 84);
insert into child_parent (child_id, parent_id) values (221, 112);
insert into child_parent (child_id, parent_id) values (222, 40);
insert into child_parent (child_id, parent_id) values (223, 67);
insert into child_parent (child_id, parent_id) values (224, 132);
insert into child_parent (child_id, parent_id) values (225, 97);
insert into child_parent (child_id, parent_id) values (226, 126);
insert into child_parent (child_id, parent_id) values (227, 20);
insert into child_parent (child_id, parent_id) values (228, 123);
insert into child_parent (child_id, parent_id) values (229, 88);
insert into child_parent (child_id, parent_id) values (230, 49);
insert into child_parent (child_id, parent_id) values (231, 92);
insert into child_parent (child_id, parent_id) values (232, 30);
insert into child_parent (child_id, parent_id) values (233, 66);
insert into child_parent (child_id, parent_id) values (234, 27);
insert into child_parent (child_id, parent_id) values (235, 141);
insert into child_parent (child_id, parent_id) values (236, 18);
insert into child_parent (child_id, parent_id) values (237, 118);
insert into child_parent (child_id, parent_id) values (238, 104);
insert into child_parent (child_id, parent_id) values (239, 91);
insert into child_parent (child_id, parent_id) values (240, 32);
insert into child_parent (child_id, parent_id) values (241, 148);
insert into child_parent (child_id, parent_id) values (242, 33);
insert into child_parent (child_id, parent_id) values (243, 130);
insert into child_parent (child_id, parent_id) values (244, 78);
insert into child_parent (child_id, parent_id) values (245, 66);
insert into child_parent (child_id, parent_id) values (246, 103);
insert into child_parent (child_id, parent_id) values (247, 35);
insert into child_parent (child_id, parent_id) values (248, 28);
insert into child_parent (child_id, parent_id) values (249, 85);
insert into child_parent (child_id, parent_id) values (250, 70);
insert into child_parent (child_id, parent_id) values (251, 70);
insert into child_parent (child_id, parent_id) values (252, 46);
insert into child_parent (child_id, parent_id) values (253, 42);
insert into child_parent (child_id, parent_id) values (254, 62);
insert into child_parent (child_id, parent_id) values (255, 55);
insert into child_parent (child_id, parent_id) values (256, 130);
insert into child_parent (child_id, parent_id) values (257, 21);
insert into child_parent (child_id, parent_id) values (258, 13);
insert into child_parent (child_id, parent_id) values (259, 77);
insert into child_parent (child_id, parent_id) values (260, 140);
insert into child_parent (child_id, parent_id) values (261, 40);
insert into child_parent (child_id, parent_id) values (262, 102);
insert into child_parent (child_id, parent_id) values (263, 34);
insert into child_parent (child_id, parent_id) values (264, 31);
insert into child_parent (child_id, parent_id) values (265, 24);
insert into child_parent (child_id, parent_id) values (266, 14);
insert into child_parent (child_id, parent_id) values (267, 1);
insert into child_parent (child_id, parent_id) values (268, 122);
insert into child_parent (child_id, parent_id) values (269, 6);
insert into child_parent (child_id, parent_id) values (270, 65);
insert into child_parent (child_id, parent_id) values (271, 110);
insert into child_parent (child_id, parent_id) values (272, 45);
insert into child_parent (child_id, parent_id) values (273, 65);
insert into child_parent (child_id, parent_id) values (274, 129);
insert into child_parent (child_id, parent_id) values (275, 10);
insert into child_parent (child_id, parent_id) values (276, 111);
insert into child_parent (child_id, parent_id) values (277, 55);
insert into child_parent (child_id, parent_id) values (278, 139);
insert into child_parent (child_id, parent_id) values (279, 109);
insert into child_parent (child_id, parent_id) values (280, 62);
insert into child_parent (child_id, parent_id) values (281, 130);
insert into child_parent (child_id, parent_id) values (282, 125);
insert into child_parent (child_id, parent_id) values (283, 106);
insert into child_parent (child_id, parent_id) values (284, 42);
insert into child_parent (child_id, parent_id) values (285, 54);
insert into child_parent (child_id, parent_id) values (286, 125);
insert into child_parent (child_id, parent_id) values (287, 36);
insert into child_parent (child_id, parent_id) values (288, 137);
insert into child_parent (child_id, parent_id) values (289, 77);
insert into child_parent (child_id, parent_id) values (290, 67);
insert into child_parent (child_id, parent_id) values (291, 27);
insert into child_parent (child_id, parent_id) values (292, 138);
insert into child_parent (child_id, parent_id) values (293, 80);
insert into child_parent (child_id, parent_id) values (294, 72);
insert into child_parent (child_id, parent_id) values (295, 40);
insert into child_parent (child_id, parent_id) values (296, 142);
insert into child_parent (child_id, parent_id) values (297, 18);
insert into child_parent (child_id, parent_id) values (298, 105);
insert into child_parent (child_id, parent_id) values (299, 85);
insert into child_parent (child_id, parent_id) values (300, 103);
